project:
  type: website
  title: "FAIR Theory"
  render:
    - presentation.qmd
    - presentation_-_ESCOP_2.qmd
    - presentation_-_FGT.qmd
    - README.qmd
  pre-render: minerva/decode.lua
  post-render:
    - cp -f _publish/README.md ./README.md
  output-dir: _publish/

