project:
  type: website
  title: "FAIR Theory"
  render:
    - index.qmd
    - presentation.qmd
    - presentation_-_ESCOP_2.qmd
    - presentation_-_FGT.qmd
    - presentation_-_TMC.qmd
  pre-render: minerva/decode.lua
  output-dir: _publish/

